import { normalizeCleaningRecord } from './cleaningProductModel';

const SOURCE_VERSION = 'servicesos-v1-2026-07-18';

function deepFreeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(deepFreeze);
    Object.freeze(value);
  }
  return value;
}
function companyMix(record) {
  return deepFreeze(normalizeCleaningRecord({
    recordType: 'company_mix',
    scope: 'system_default',
    category: 'company method',
    classification: 'cleaning',
    status: 'candidate',
    employeeVisible: false,
    requiredTools: [],
    requiredPPE: ['Gloves'],
    compatibleSurfaces: [],
    prohibitedSurfaces: [],
    dangerousCombinations: ['Never combine with another cleaner.'],
    evidence: ['Jamie-approved ServicesOS V1 starter method'],
    ownerReviewNotes: '',
    ingredients: [],
    measurements: [],
    formulaVariants: [],
    expectedYield: '',
    bottleSize: '',
    approvedContainer: '',
    mixingOrder: [],
    preparationFrequency: '',
    mixedOnLabelRequired: true,
    discardDateLabelRequired: true,
    createdAt: SOURCE_VERSION,
    createdBy: 'system',
    updatedAt: SOURCE_VERSION,
    updatedBy: 'system',
    ...record,
  }));
}

export const STARTER_CLEANING_METHODS = deepFreeze([
  companyMix({
    id: 'ab-dawn-vinegar-shower-cleaner',
    name: 'Dawn and Vinegar Shower Cleaner',
    category: 'shower cleaner',
    status: 'owner_tested',
    intendedUses: ['Soap scum', 'Hard-water film', 'Mineral buildup', 'Owner-reported calcium buildup'],
    compatibleSurfaces: ['Owner-approved acid-safe shower surfaces'],
    prohibitedSurfaces: ['Marble', 'Granite', 'Travertine', 'Limestone', 'Natural stone', 'Mirrors', 'Unknown or acid-sensitive finishes', 'Specialty-coated glass unless manufacturer-approved'],
    requiredTools: ['Dedicated chemical-resistant spray bottle', 'Non-scratch cleaning cloth or pad'],
    dwellTime: '5–10 minutes',
    applicationInstructions: 'Apply only to an approved surface. Test unfamiliar surfaces before broader use.',
    rinseInstructions: 'Rinse thoroughly.',
    dryingInstructions: 'Dry the surface after rinsing.',
    dangerousCombinations: ['Never mix with bleach.', 'Never apply over bleach residue.', 'Never combine with another cleaner.'],
    storageInstructions: 'Store in the dedicated labeled container away from incompatible chemicals.',
    shelfLife: '14 days',
    ownerReviewNotes: 'Cleaning only. Not a sanitizer or disinfectant.',
    ingredients: ['Regular distilled white vinegar', 'Warm water', 'Basic Dawn dish soap'],
    formulaVariants: [
      {
        id: 'standard',
        name: 'Standard',
        measurements: ['2 cups regular distilled white vinegar', '1 cup warm water', '2 tablespoons basic Dawn dish soap'],
        expectedYield: 'Approximately 25 oz',
      },
      {
        id: 'heavy-buildup',
        name: 'Heavy buildup',
        measurements: ['2 cups regular distilled white vinegar', '1/2 cup warm water', '3 tablespoons basic Dawn dish soap'],
        expectedYield: 'Approximately 21.5 oz',
      },
    ],
    bottleSize: '32 oz',
    approvedContainer: 'Dedicated 32 oz chemical-resistant Zep spray bottle',
    mixingOrder: ['Add warm water.', 'Add distilled white vinegar.', 'Add Dawn slowly to limit foaming.', 'Close and gently combine.'],
    preparationFrequency: 'Prepare as needed and discard after 14 days.',
  }),
  companyMix({
    id: 'ab-everyday-mild-surface-cleaner',
    name: 'Everyday Mild Surface Cleaner',
    intendedUses: ['Routine cleaning of sealed washable surfaces'],
    prohibitedSurfaces: ['Unfinished wood', 'Electronics', 'Unknown finishes', 'Waxed surfaces', 'Unapproved natural stone'],
    ingredients: ['Warm water', 'Basic Dawn dish soap'],
    measurements: ['4 cups warm water', '1 teaspoon basic Dawn dish soap'],
    preparationFrequency: 'Prepare fresh daily.',
    applicationInstructions: 'Use only on sealed washable surfaces approved by the owner or manufacturer.',
  }),
  companyMix({
    id: 'ab-kitchen-grease-cleaner',
    name: 'Kitchen Grease Cleaner',
    category: 'degreasing cleaner',
    intendedUses: ['Kitchen grease on approved washable surfaces'],
    prohibitedSurfaces: ['Unfinished wood', 'Electrical controls', 'Seams', 'Outlets', 'Vents'],
    ingredients: ['Warm water', 'Basic Dawn dish soap'],
    formulaVariants: [
      { id: 'standard', name: 'Standard', measurements: ['2 cups warm water', '1 teaspoon basic Dawn dish soap'] },
      { id: 'heavy', name: 'Heavy', measurements: ['2 cups warm water', '2 teaspoons basic Dawn dish soap'] },
    ],
    applicationInstructions: 'Apply away from electrical controls, seams, outlets, and vents.',
  }),
  companyMix({
    id: 'ab-window-glass-vinegar-cleaner',
    name: 'Window Glass Vinegar Cleaner',
    category: 'glass cleaner',
    intendedUses: ['Ordinary uncoated window glass'],
    compatibleSurfaces: ['Ordinary uncoated window glass'],
    prohibitedSurfaces: ['Mirrors', 'Tinted glass', 'Coated glass', 'Screens', 'Nearby natural stone'],
    ingredients: ['Distilled white vinegar', 'Water'],
    measurements: ['1 cup distilled white vinegar', '1 cup water'],
    dangerousCombinations: ['Never mix with bleach.', 'Never combine with another cleaner.'],
  }),
  companyMix({
    id: 'ab-mirror-cleaner',
    name: 'Mirror Cleaner',
    category: 'mirror cleaner',
    intendedUses: ['Owner-approved mirrors'],
    compatibleSurfaces: ['Owner-approved mirrors'],
    prohibitedSurfaces: ['Mirror edges and backing'],
    ingredients: ['Distilled water', 'Basic Dawn dish soap'],
    measurements: ['2 cups distilled water', '1/4 teaspoon basic Dawn dish soap'],
    applicationInstructions: 'Apply to the cloth, not directly to the mirror. Keep away from edges and backing.',
    dryingInstructions: 'Dry immediately.',
  }),
  companyMix({
    id: 'ab-baking-soda-cleaning-paste',
    name: 'Baking-Soda Cleaning Paste',
    category: 'mild abrasive cleaner',
    intendedUses: ['Owner-approved spot cleaning'],
    prohibitedSurfaces: ['Polished stone', 'Acrylic or fiberglass unless tested', 'Glossy finishes', 'Coated fixtures', 'Easily scratched surfaces'],
    ingredients: ['Baking soda', 'Water'],
    measurements: ['3 tablespoons baking soda', '1 tablespoon water'],
    applicationInstructions: 'This paste is mildly abrasive. Test the approved surface before broader use.',
  }),
  companyMix({
    id: 'ab-hard-floor-maintenance-cleaner',
    name: 'Hard-Floor Maintenance Cleaner',
    category: 'floor cleaner',
    intendedUses: ['Manufacturer-approved vinyl', 'Manufacturer-approved LVP', 'Glazed ceramic tile', 'Sealed non-stone flooring'],
    compatibleSurfaces: ['Manufacturer-approved vinyl', 'Manufacturer-approved LVP', 'Glazed ceramic tile', 'Sealed non-stone flooring'],
    prohibitedSurfaces: ['Hardwood', 'Unapproved laminate', 'Natural stone', 'Cork', 'Waxed floors', 'Unknown flooring'],
    ingredients: ['Warm water', 'Basic Dawn dish soap'],
    measurements: ['1 gallon warm water', '1 teaspoon basic Dawn dish soap'],
    applicationInstructions: 'Use only after confirming the flooring manufacturer permits the method.',
  }),
  companyMix({
    id: 'ab-stainless-steel-everyday-method',
    name: 'Stainless-Steel Everyday Method',
    category: 'stainless-steel cleaner',
    intendedUses: ['Owner-approved uncoated stainless steel'],
    compatibleSurfaces: ['Owner-approved uncoated stainless steel'],
    prohibitedSurfaces: ['Unapproved coated appliances'],
    ingredients: ['Warm water', 'Basic Dawn dish soap'],
    measurements: ['2 cups warm water', '1/2 teaspoon basic Dawn dish soap'],
    applicationInstructions: 'Wipe with the grain. Do not use abrasives or chlorine products.',
    rinseInstructions: 'Wipe with clean water.',
    dryingInstructions: 'Dry immediately.',
    dangerousCombinations: ['Do not use with chlorine products.', 'Never combine with another cleaner.'],
  }),
  companyMix({
    id: 'ab-routine-toilet-bowl-cleaning-method',
    name: 'Routine Toilet-Bowl Cleaning Method',
    category: 'toilet-bowl cleaner',
    intendedUses: ['Routine toilet-bowl cleaning'],
    ingredients: ['Baking soda', 'Basic Dawn dish soap'],
    measurements: ['1/4 cup baking soda', '1 teaspoon basic Dawn dish soap'],
    applicationInstructions: 'Routine cleaning only.',
    dangerousCombinations: ['Never apply over toilet cleaner, bleach, acid, or another chemical.'],
  }),
  companyMix({
    id: 'ab-dry-baking-soda-odor-control-method',
    name: 'Dry Baking-Soda Odor-Control Method',
    category: 'odor control',
    intendedUses: ['Approved dry odor-control uses'],
    prohibitedSurfaces: ['Carpet or upholstery without owner approval'],
    requiredPPE: [],
    ingredients: ['Dry baking soda'],
    measurements: ['Use only the owner-approved amount for the approved dry application.'],
    applicationInstructions: 'Do not broadly apply to carpet or upholstery without approval.',
    ownerReviewNotes: 'Cleaning/odor control only. Not sanitizing.',
  }),
]);

export function getStarterCleaningMethods() {
  return STARTER_CLEANING_METHODS;
}
