import { useEffect, useState } from 'react';
import { createAddOn, listOwnerAddOns, updateAddOn } from '../services/addOnCatalogService';

const empty = { label:'', description:'', price:'', duration:'' };
export default function AddOnCatalogSettings() {
  const [items,setItems]=useState([]); const [form,setForm]=useState(empty); const [editingId,setEditingId]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{let active=true;listOwnerAddOns().then(values=>{if(active)setItems(values);}).catch(()=>{if(active)setError('Add-ons could not be loaded. Try again.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const values=()=>({ label:form.label.trim(), description:form.description.trim(), active:true, priceCents:Math.round(Number(form.price)*100), durationMinutes:Number(form.duration) });
  const submit=async event=>{event.preventDefault();setError('');const existing=items.find(item=>item.id===editingId);const next={...values(),active:existing?.active??true};if(!next.label||!Number.isInteger(next.priceCents)||next.priceCents<0||!Number.isInteger(next.durationMinutes)||next.durationMinutes<1){setError('Enter a name, non-negative price, and duration in whole minutes.');return;}setSaving(true);try{const saved=editingId?await updateAddOn(editingId,next):await createAddOn(next);setItems(current=>(editingId?current.map(value=>value.id===saved.id?saved:value):[...current,saved]).sort((a,b)=>a.label.localeCompare(b.label)));setForm(empty);setEditingId('');}catch{setError('Add-on could not be saved. Try again.');}finally{setSaving(false);}};
  const edit=item=>{setEditingId(item.id);setForm({label:item.label,description:item.description,price:(item.priceCents/100).toFixed(2),duration:String(item.durationMinutes)});setError('');};
  const toggle=async item=>{setSaving(true);setError('');try{const saved=await updateAddOn(item.id,{label:item.label,description:item.description,active:!item.active,priceCents:item.priceCents,durationMinutes:item.durationMinutes});setItems(current=>current.map(value=>value.id===saved.id?saved:value));}catch{setError('Add-on could not be updated. Try again.');}finally{setSaving(false);}};
  return <section className="v1-card" aria-labelledby="add-on-catalog-title" style={{padding:24}}><h2 id="add-on-catalog-title" style={{marginTop:0}}>Add-on catalog</h2><p className="v1-muted">Set the authoritative price and working time for optional services.</p>{loading&&<p role="status">Loading add-ons...</p>}{error&&<p role="alert" style={{color:'#991b1b'}}>{error}</p>}{!loading&&<>{items.length===0?<p>No add-ons configured.</p>:<div style={{display:'grid',gap:10,marginBottom:20}}>{items.map(item=><div key={item.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,borderBottom:'1px solid #e2e8f0',paddingBottom:10}}><div><strong>{item.label}</strong><div>${(item.priceCents/100).toFixed(2)} · {item.durationMinutes} minutes · {item.active?'Active':'Inactive'}</div>{item.description&&<small>{item.description}</small>}</div><div style={{display:'flex',gap:8}}><button type="button" disabled={saving} onClick={()=>edit(item)}>Edit</button><button type="button" disabled={saving} onClick={()=>toggle(item)}>{item.active?'Deactivate':'Activate'}</button></div></div>)}</div>}<form aria-label={editingId?'Edit add-on':'Add add-on'} onSubmit={submit} style={{display:'grid',gap:12}}><label>Name<input aria-label="Add-on name" value={form.label} maxLength={100} onChange={e=>setForm({...form,label:e.target.value})}/></label><label>Description<input aria-label="Add-on description" value={form.description} maxLength={300} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Price in dollars<input aria-label="Add-on price" type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Duration in minutes<input aria-label="Add-on duration" type="number" min="1" step="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><button className="v1-button v1-button-primary" disabled={saving} type="submit">{saving?'Saving...':editingId?'Save add-on':'Add add-on'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId('');setForm(empty);}}>Cancel</button>}</form></>}</section>;
}
