import { useEffect, useState } from 'react';
import { createService, listOwnerServices, updateService } from '../services/serviceCatalogService';

const empty={name:'',serviceType:'standard',price:'',duration:''};
const typeLabels={standard:'Standard',deep:'Deep clean',moveout:'Move-in / move-out',construction:'Post-construction'};

export default function ServiceCatalogSettings(){
  const [items,setItems]=useState([]); const [form,setForm]=useState(empty); const [editingId,setEditingId]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{let active=true;listOwnerServices().then(values=>{if(active)setItems(values);}).catch(()=>{if(active)setError('Services could not be loaded. Try again.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const values=()=>({name:form.name.trim(),serviceType:form.serviceType,active:items.find(item=>item.id===editingId)?.active??true,priceCents:Math.round(Number(form.price)*100),durationMinutes:Number(form.duration)});
  const submit=async event=>{event.preventDefault();setError('');const next=values();if(!next.name||!Number.isInteger(next.priceCents)||next.priceCents<1||!Number.isInteger(next.durationMinutes)||next.durationMinutes<1){setError('Enter a name, positive price, and duration in whole minutes.');return;}setSaving(true);try{const saved=editingId?await updateService(editingId,next):await createService(next);setItems(current=>(editingId?current.map(item=>item.id===saved.id?saved:item):[...current,saved]).sort((a,b)=>a.name.localeCompare(b.name)));setForm(empty);setEditingId('');}catch{setError('Service could not be saved. Try again.');}finally{setSaving(false);}};
  const edit=item=>{setEditingId(item.id);setForm({name:item.name,serviceType:item.serviceType,price:(item.priceCents/100).toFixed(2),duration:String(item.durationMinutes)});setError('');};
  const toggle=async item=>{setSaving(true);setError('');try{const saved=await updateService(item.id,{...item,active:!item.active});setItems(current=>current.map(value=>value.id===saved.id?saved:value));}catch{setError('Service could not be updated. Try again.');}finally{setSaving(false);}};
  return <section className="v1-card" aria-labelledby="service-catalog-title" style={{padding:24}}><h2 id="service-catalog-title" style={{marginTop:0}}>Services and pricing</h2><p className="v1-muted">Set the authoritative starting price and working time for each service.</p>{loading&&<p role="status">Loading services...</p>}{error&&<p role="alert" style={{color:'#991b1b'}}>{error}</p>}{!loading&&<>{items.length===0?<p>No services configured. Existing estimate and booking behavior remains available until the first service is added.</p>:<div style={{display:'grid',gap:10,marginBottom:20}}>{items.map(item=><div key={item.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,borderBottom:'1px solid #e2e8f0',paddingBottom:10}}><div><strong>{item.name}</strong><div>{typeLabels[item.serviceType]} · ${(item.priceCents/100).toFixed(2)} · {item.durationMinutes} minutes · {item.active?'Active':'Inactive'}</div></div><div style={{display:'flex',gap:8}}><button type="button" disabled={saving} onClick={()=>edit(item)}>Edit</button><button type="button" disabled={saving} onClick={()=>toggle(item)}>{item.active?'Deactivate':'Activate'}</button></div></div>)}</div>}<form aria-label={editingId?'Edit service':'Add service'} onSubmit={submit} style={{display:'grid',gap:12}}><label>Name<input aria-label="Service name" value={form.name} maxLength={100} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Service classification<select aria-label="Service classification" value={form.serviceType} onChange={e=>setForm({...form,serviceType:e.target.value})}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Starting price in dollars<input aria-label="Service price" type="number" min="0.01" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Duration in minutes<input aria-label="Service duration" type="number" min="1" step="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><button className="v1-button v1-button-primary" disabled={saving} type="submit">{saving?'Saving...':editingId?'Save service':'Add service'}</button>{editingId&&<button type="button" onClick={()=>{setEditingId('');setForm(empty);}}>Cancel</button>}</form></>}</section>;
}
