const { membershipContains, normalizedText } = require('./ownerOnboardingBootstrapGateway');
const { verifyCanonicalEmployee } = require('./employeeAuthorization');
const { bookingMatchesEmployeeJobVisibility, localDateKey } = require('./employeeJobPacketProjection');

const ORIGINS=new Set(['https://servicesos.netlify.app','http://127.0.0.1:5173','http://localhost:5173','http://127.0.0.1:5174','http://localhost:5174']);
const DISPOSITIONS=new Set(['same_visit_fits','same_visit_additional_time','future_visit','declined']);
class ExtraWorkError extends Error{constructor(message,code='invalid_request',status=400){super(message);this.code=code;this.status=status;}}
const fail=(message,code,status)=>{throw new ExtraWorkError(message,code,status);};
const text=(value,max)=>{const result=normalizedText(value)||'';if(result.length>max)fail('Invalid extra-work request.');return result;};
const validId=value=>{const id=text(value,128);return id&&!id.includes('/')&&id!=='.'&&id!=='..'?id:fail('Invalid extra-work request.');};
const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).sort().join('|')===keys.slice().sort().join('|');

function parseRequest(body){
  const action=body?.action;
  const shapes={employee_submit:['action','bookingId','items','customRequest','employeeNote'],employee_list:['action','bookingId'],owner_list:['action','bookingId'],owner_review:['action','bookingId','requestId','disposition','customPriceCents','customDurationMinutes','ownerNote','authorizedExtensionMinutes']};
  if(!shapes[action]||!exact(body,shapes[action]))fail('Invalid extra-work request.');
  const request={action,bookingId:validId(body.bookingId)};
  if(action==='employee_submit'){
    if(!Array.isArray(body.items)||body.items.length>20)fail('Invalid extra-work request.');
    request.items=body.items.map(item=>{if(!exact(item,['addOnId','quantity'])||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>10)fail('Invalid extra-work request.');return{addOnId:validId(item.addOnId),quantity:item.quantity};});
    if(new Set(request.items.map(item=>item.addOnId)).size!==request.items.length)fail('Invalid extra-work request.');
    if(body.customRequest!==null){if(!exact(body.customRequest,['description','context']))fail('Invalid extra-work request.');request.customRequest={description:text(body.customRequest.description,300),context:text(body.customRequest.context,500)};if(!request.customRequest.description)fail('Invalid extra-work request.');}else request.customRequest=null;
    request.employeeNote=text(body.employeeNote,500);if(!request.items.length&&!request.customRequest)fail('Invalid extra-work request.');
  }
  if(action==='owner_review'){
    request.requestId=validId(body.requestId);request.disposition=body.disposition;if(!DISPOSITIONS.has(request.disposition))fail('Invalid review decision.');
    request.customPriceCents=body.customPriceCents;if(request.customPriceCents!==null&&(!Number.isInteger(request.customPriceCents)||request.customPriceCents<0||request.customPriceCents>10000000))fail('Invalid review decision.');
    request.customDurationMinutes=body.customDurationMinutes;if(request.customDurationMinutes!==null&&(!Number.isInteger(request.customDurationMinutes)||request.customDurationMinutes<1||request.customDurationMinutes>1440))fail('Invalid review decision.');
    request.authorizedExtensionMinutes=body.authorizedExtensionMinutes;if(!Number.isInteger(request.authorizedExtensionMinutes)||request.authorizedExtensionMinutes<0||request.authorizedExtensionMinutes>1440)fail('Invalid review decision.');
    if(request.disposition==='same_visit_additional_time'&&request.authorizedExtensionMinutes<1)fail('Additional time is required.','validation_failed',422);
    if(request.disposition!=='same_visit_additional_time'&&request.authorizedExtensionMinutes!==0)fail('Invalid review decision.');
    request.ownerNote=text(body.ownerNote,500);
  }
  return request;
}

async function identityContext(admin,identity){const uid=normalizedText(identity?.uid);if(!uid)fail('Authentication required.','unauthenticated',401);const db=admin.firestore();const profileSnap=await db.collection('users').doc(uid).get();if(!profileSnap.exists)fail('Access unavailable.','forbidden',403);const profile=profileSnap.data()||{};const tenantId=normalizedText(profile.tenantId);if(!tenantId||tenantId==='DEFAULT'||profile.status!=='active')fail('Access unavailable.','forbidden',403);const tenantSnap=await db.collection('tenants').doc(tenantId).get();if(!tenantSnap.exists)fail('Access unavailable.','forbidden',403);return{uid,tenantId,profile,tenant:tenantSnap.data()||{}};}
function requireOwner(context){if(context.profile.role!=='admin'||!membershipContains(context.tenant.adminUsers,context.uid))fail('Access unavailable.','forbidden',403);}
function baseline(booking){const approved=booking.approvedJobScope;const control=booking.jobScopeControl;if(!approved||!Number.isInteger(approved.version)||typeof approved.scopeHash!=='string'||!approved.scopeHash||control?.approvedVersion!==approved.version||control?.approvedScopeHash!==approved.scopeHash)fail('Approved scope is unavailable.','scope_unavailable',409);return{version:approved.version,scopeHash:approved.scopeHash};}
const employeeView=record=>({id:record.id,status:record.status,requestedAt:record.submission.requestedAt,scope:record.submission.scope,items:record.submission.items.map(item=>({id:item.id,label:item.label,quantity:item.quantity,lineTotalCents:item.lineTotalCents,durationMinutes:item.durationMinutes})),customRequest:record.submission.customRequest?{description:record.submission.customRequest.description}:null,disposition:record.ownerReview?.disposition||null});
const ownerView=record=>({id:record.id,status:record.status,submission:record.submission,ownerReview:record.ownerReview||null});

async function employeeSubmit({admin,employee,request,now}){const db=admin.firestore();const bookingRef=db.collection('tenants').doc(employee.tenantId).collection('bookings').doc(request.bookingId);const requestRef=bookingRef.collection('extraWorkRequests').doc();return db.runTransaction(async tx=>{const bookingSnap=await tx.get(bookingRef);if(!bookingSnap.exists)fail('Job unavailable.','job_unavailable',404);const booking=bookingSnap.data()||{};const today=localDateKey(now,employee.tenantTimeZone);if(!bookingMatchesEmployeeJobVisibility(booking,{uid:employee.uid,today,timeZone:employee.tenantTimeZone}))fail('Job unavailable.','job_unavailable',404);const scope=baseline(booking);const items=[];for(const selected of request.items){const catalogRef=db.collection('tenants').doc(employee.tenantId).collection('addOnCatalog').doc(selected.addOnId);const snap=await tx.get(catalogRef);const value=snap.exists?snap.data()||{}:{};if(!snap.exists||value.active!==true||!Number.isInteger(value.priceCents)||!Number.isInteger(value.durationMinutes))fail('Add-on unavailable.','addon_unavailable',409);items.push({id:snap.id||selected.addOnId,label:text(value.label,100),priceCents:value.priceCents,durationMinutes:value.durationMinutes,quantity:selected.quantity,lineTotalCents:value.priceCents*selected.quantity,totalDurationMinutes:value.durationMinutes*selected.quantity});}
    const submittedAt=now.toISOString();const record={id:requestRef.id,bookingId:request.bookingId,status:'submitted',submission:{scope,employeeUid:employee.uid,requestedAt:submittedAt,items,customRequest:request.customRequest,employeeNote:request.employeeNote}};tx.create(requestRef,record);return{success:true,request:employeeView(record)};});}
async function listRequests({admin,context,employee,request,owner}){const tenantId=owner?context.tenantId:employee.tenantId;const ref=admin.firestore().collection('tenants').doc(tenantId).collection('bookings').doc(request.bookingId);const booking=await ref.get();if(!booking.exists)fail('Job unavailable.','job_unavailable',404);if(owner)requireOwner(context);else{const today=localDateKey(new Date(),employee.tenantTimeZone);if(!bookingMatchesEmployeeJobVisibility(booking.data()||{},{uid:employee.uid,today,timeZone:employee.tenantTimeZone}))fail('Job unavailable.','job_unavailable',404);}const snap=await ref.collection('extraWorkRequests').limit(50).get();return{success:true,requests:snap.docs.map(doc=>{const value={id:doc.id,...doc.data()};return owner?ownerView(value):employeeView(value);})};}
async function ownerReview({admin,context,request,now}){requireOwner(context);const db=admin.firestore();const bookingRef=db.collection('tenants').doc(context.tenantId).collection('bookings').doc(request.bookingId);const ref=bookingRef.collection('extraWorkRequests').doc(request.requestId);return db.runTransaction(async tx=>{const [bookingSnap,snap]=await Promise.all([tx.get(bookingRef),tx.get(ref)]);if(!bookingSnap.exists||!snap.exists)fail('Request unavailable.','request_unavailable',404);const record={id:request.requestId,...snap.data()};const current=baseline(bookingSnap.data()||{});if(current.version!==record.submission?.scope?.version||current.scopeHash!==record.submission?.scope?.scopeHash)fail('Approved scope changed.','scope_changed',409);if(record.status!=='submitted')fail('Request was already reviewed.','review_conflict',409);if(record.submission.customRequest&&request.disposition!=='declined'&&request.customPriceCents===null)fail('Custom price is required.','validation_failed',422);const ownerReview={reviewedAt:now.toISOString(),reviewedByUid:context.uid,disposition:request.disposition,customPriceCents:record.submission.customRequest?request.customPriceCents:null,customDurationMinutes:record.submission.customRequest?request.customDurationMinutes:null,ownerNote:request.ownerNote,authorizedExtensionMinutes:request.authorizedExtensionMinutes};const status=request.disposition==='declined'?'declined':'approval_ready';tx.update(ref,{status,ownerReview});return{success:true,request:ownerView({...record,status,ownerReview})};});}

function createExtraWorkGatewayHandler({admin,now=()=>new Date()}){return async(req,res)=>{const origin=req.headers?.origin;if(ORIGINS.has(origin)){res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');}res.set('Access-Control-Allow-Methods','POST, OPTIONS');res.set('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS')return res.status(204).send('');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',code:'method_not_allowed'});const header=req.headers?.authorization||req.headers?.Authorization||'';const token=header.startsWith('Bearer ')?header.slice(7).trim():'';if(!token)return res.status(401).json({error:'Authentication required',code:'unauthenticated'});let identity;try{identity=await admin.auth().verifyIdToken(token);}catch{return res.status(401).json({error:'Authentication required',code:'unauthenticated'});}try{const request=parseRequest(req.body);if(request.action.startsWith('employee_')){const employee=await verifyCanonicalEmployee({admin,uid:identity.uid});const result=request.action==='employee_submit'?await employeeSubmit({admin,employee,request,now:now()}):await listRequests({admin,employee,request,owner:false});return res.status(200).json(result);}const context=await identityContext(admin,identity);const result=request.action==='owner_list'?await listRequests({admin,context,request,owner:true}):await ownerReview({admin,context,request,now:now()});return res.status(200).json(result);}catch(error){if(error instanceof ExtraWorkError||error?.name==='EmployeeAuthorizationError')return res.status(error.status||403).json({error:'Extra-work request unavailable.',code:error.code||'forbidden'});return res.status(500).json({error:'Extra-work requests are temporarily unavailable.',code:'extra_work_unavailable'});}};}
module.exports={DISPOSITIONS,ExtraWorkError,createExtraWorkGatewayHandler,employeeSubmit,parseRequest};
