const test = require('node:test');
const assert = require('node:assert/strict');
const { createEmployeeTeamGatewayHandler, createResendActivationSender, parseRequest, projectEmployee } = require('../employeeTeamGateway');

function fixture({ uid='owner-a', profile, tenant, authUsers, failTransaction=false }={}) {
  const state = new Map(Object.entries({
    'users/owner-a': { role:'admin', status:'active', tenantId:'tenant-a' },
    'users/employee-caller': { role:'employee', status:'active', tenantId:'tenant-a' },
    'users/customer-caller': { role:'customer', status:'active', tenantId:'tenant-a' },
    'users/owner-b': { role:'admin', status:'active', tenantId:'tenant-b' },
    'tenants/tenant-a': { adminUsers:['owner-a'], users:['owner-a'] },
    'tenants/tenant-b': { adminUsers:['owner-b'], users:['owner-b'] },
    ...(profile?{'users/owner-a':profile}:{}), ...(tenant?{'tenants/tenant-a':tenant}:{}),
  }));
  const users = new Map(Object.entries(authUsers || {})); const sent=[]; const deleted=[];
  const snap = ref => ({ exists:state.has(ref.path), data:()=>state.get(ref.path) });
  class Ref { constructor(path){this.path=path;this.id=path.split('/').at(-1);} collection(name){return new Query(`${this.path}/${name}`);} get(){return Promise.resolve(snap(this));} update(v){state.set(this.path,{...state.get(this.path),...structuredClone(v)});return Promise.resolve();} }
  class Query { constructor(path){this.path=path;this.filters=[];this.max=Infinity;} doc(id){return new Ref(`${this.path}/${id}`);} where(field,op,value){this.filters.push([field,op,value]);return this;} limit(n){this.max=n;return this;} async get(){const prefix=`${this.path}/`;const docs=[...state].filter(([path,value])=>path.startsWith(prefix)&&!path.slice(prefix.length).includes('/')&&this.filters.every(([field,,expected])=>value[field]===expected)).slice(0,this.max).map(([path,value])=>({id:path.slice(prefix.length),data:()=>value}));return{docs};} }
  const transaction={get:ref=>Promise.resolve(snap(ref)),create:(ref,v)=>{state.set(ref.path,structuredClone(v));},update:(ref,v)=>{state.set(ref.path,{...state.get(ref.path),...structuredClone(v)});}};
  const db={collection:name=>new Query(name),runTransaction:async fn=>{if(failTransaction)throw new Error('write failed');return fn(transaction);}};
  const auth={verifyIdToken:async()=>({uid}),getUserByEmail:async email=>{const found=[...users.values()].find(user=>user.email===email);if(!found){const e=new Error();e.code='auth/user-not-found';throw e;}return found;},createUser:async input=>{const record={uid:`employee-${users.size+1}`,email:input.email};users.set(record.uid,record);return record;},deleteUser:async id=>{deleted.push(id);users.delete(id);},generatePasswordResetLink:async email=>`https://example.test/reset?email=${encodeURIComponent(email)}`};
  return { admin:{firestore:()=>db,auth:()=>auth}, state, users, sent, deleted, sendActivationEmail:async value=>{sent.push(value);} };
}

function response(){return{statusCode:0,payload:null,set(){},status(code){this.statusCode=code;return this;},json(value){this.payload=value;return this;},send(){return this;}};}
async function call(f,body={action:'owner_provision',name:'Avery Employee',email:'avery@example.test',phone:''},headers={authorization:'Bearer token'}){const res=response();await createEmployeeTeamGatewayHandler({admin:f.admin,sendActivationEmail:f.sendActivationEmail})({method:'POST',headers,body},res);return res;}

test('request parser rejects tenant, uid, role, actor and timestamp forging',()=>{for(const key of ['tenantId','uid','role','status','membership','createdByUid','createdAt'])assert.throws(()=>parseRequest({action:'owner_provision',name:'A',email:'a@example.test',phone:'',[key]:'x'}));for(const key of ['tenantId','uid','role','status','membership','updatedByUid','updatedAt'])assert.throws(()=>parseRequest({action:'owner_set_payment_permission',employeeUid:'employee-a',canCollectPayments:true,[key]:'x'}));});
test('missing payment permission projects false',()=>{assert.equal(projectEmployee('employee-a',{name:'A',email:'a@example.test',status:'active',activationStatus:'authenticated'}).canCollectPayments,false);});
test('authorized owner provisions canonical UID identity and sends link only to employee',async()=>{const f=fixture();const res=await call(f);assert.equal(res.statusCode,200);const employee=res.payload.employee;assert.equal(f.state.get(`users/${employee.uid}`).role,'employee');assert.equal(f.state.get(`users/${employee.uid}`).status,'active');assert.equal(f.state.get(`users/${employee.uid}`).tenantId,'tenant-a');assert.ok(f.state.get('tenants/tenant-a').users.includes(employee.uid));assert.equal(f.state.get('tenants/tenant-a').adminUsers.includes(employee.uid),false);assert.equal(f.state.get(`tenants/tenant-a/employees/${employee.uid}`).authUid,employee.uid);assert.equal(f.sent.length,1);assert.equal(f.sent[0].email,'avery@example.test');assert.equal(JSON.stringify(res.payload).includes('reset?'),false);assert.equal(JSON.stringify([...f.state]).includes('reset?'),false);});
test('new employees default payment collection permission to false',async()=>{const f=fixture();const res=await call(f);const record=f.state.get(`tenants/tenant-a/employees/${res.payload.employee.uid}`);assert.equal(res.payload.employee.canCollectPayments,false);assert.equal(record.canCollectPayments,false);assert.equal(record.paymentPermissionUpdatedAt,null);assert.equal(record.paymentPermissionUpdatedByUid,null);});
test('unauthenticated, employee, customer, and admin without canonical tenant membership are denied',async()=>{assert.equal((await call(fixture(),undefined,{})).statusCode,401);for(const uid of ['employee-caller','customer-caller'])assert.equal((await call(fixture({uid}))).statusCode,403);assert.equal((await call(fixture({tenant:{adminUsers:['other-owner'],users:['other-owner']}}))).statusCode,403);});
test('same-tenant canonical repeat is idempotent and does not send again',async()=>{const f=fixture();const first=await call(f);f.sent.length=0;const second=await call(f);assert.equal(second.statusCode,200);assert.equal(second.payload.reused,true);assert.equal(f.sent.length,0);assert.equal(f.users.size,1);});
test('cross-tenant, different-role, and orphan Auth accounts fail closed',async()=>{for(const setup of [
  {user:{uid:'existing',email:'avery@example.test'},profile:{role:'employee',status:'active',tenantId:'tenant-b'},employee:{authUid:'existing',email:'avery@example.test',status:'active'}},
  {user:{uid:'existing',email:'avery@example.test'},profile:{role:'admin',status:'active',tenantId:'tenant-a'},employee:{authUid:'existing',email:'avery@example.test',status:'active'}},
  {user:{uid:'existing',email:'avery@example.test'}},
]){const f=fixture({authUsers:{existing:setup.user}});if(setup.profile)f.state.set('users/existing',setup.profile);if(setup.employee)f.state.set('tenants/tenant-a/employees/existing',setup.employee);if(setup.profile?.tenantId==='tenant-a')f.state.set('tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','existing']});assert.equal((await call(f)).statusCode,409);}});
test('Firestore failure deletes only a newly-created Auth user',async()=>{const f=fixture({failTransaction:true});assert.equal((await call(f)).statusCode,500);assert.deepEqual(f.deleted,['employee-1']);});
test('activation failure remains recoverable without creating a second identity',async()=>{const f=fixture();f.sendActivationEmail=async()=>{throw new Error('down');};const first=await call(f);assert.equal(first.statusCode,503);assert.equal(f.users.size,1);assert.equal([...f.state.entries()].find(([p])=>p.includes('/employees/'))[1].activationStatus,'delivery_failed');});
test('owner-only state is canonical, creates no employee, and can change to employees',async()=>{const f=fixture();let res=await call(f,{action:'owner_set_workforce_mode',workforceMode:'owner_only'});assert.equal(res.statusCode,200);assert.equal(f.state.get('tenants/tenant-a').workforceMode,'owner_only');assert.equal([...f.state.keys()].some(path=>path.includes('/employees/')),false);res=await call(f,{action:'owner_set_workforce_mode',workforceMode:'employees'});assert.equal(res.statusCode,200);assert.equal(f.state.get('tenants/tenant-a').workforceMode,'employees');});
test('owner list excludes legacy random-ID and contradictory employee records',async()=>{const f=fixture();f.state.set('tenants/tenant-a/employees/legacy-random',{name:'Legacy',email:'legacy@example.test',status:'active'});f.state.set('tenants/tenant-a/employees/employee-a',{authUid:'employee-a',name:'Avery',email:'avery@example.test',status:'active'});f.state.set('users/employee-a',{role:'employee',status:'active',tenantId:'tenant-a',email:'avery@example.test'});f.state.set('tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','employee-a']});const res=await call(f,{action:'owner_list'});assert.equal(res.statusCode,200);assert.deepEqual(res.payload.employees.map(item=>item.uid),['employee-a']);assert.equal(res.payload.workforceMode,null);});
test('authorized owner enables and disables payment permission without changing unrelated employee fields',async()=>{const f=fixture();f.state.set('users/employee-a',{role:'employee',status:'active',tenantId:'tenant-a',email:'avery@example.test'});f.state.set('tenants/tenant-a/employees/employee-a',{authUid:'employee-a',name:'Avery',email:'avery@example.test',phone:'555',status:'active',activationStatus:'authenticated',unrelated:'preserved'});f.state.set('tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','employee-a']});let res=await call(f,{action:'owner_set_payment_permission',employeeUid:'employee-a',canCollectPayments:true});assert.equal(res.statusCode,200);assert.equal(res.payload.employee.canCollectPayments,true);let record=f.state.get('tenants/tenant-a/employees/employee-a');assert.equal(record.canCollectPayments,true);assert.equal(record.paymentPermissionUpdatedByUid,'owner-a');assert.match(record.paymentPermissionUpdatedAt,/Z$/);assert.equal(record.unrelated,'preserved');res=await call(f,{action:'owner_set_payment_permission',employeeUid:'employee-a',canCollectPayments:false});assert.equal(res.statusCode,200);assert.equal(res.payload.employee.canCollectPayments,false);assert.equal(f.state.get('tenants/tenant-a/employees/employee-a').canCollectPayments,false);});
test('payment permission mutation rejects unauthorized callers and invalid canonical targets',async()=>{const body={action:'owner_set_payment_permission',employeeUid:'employee-a',canCollectPayments:true};for(const uid of ['employee-caller','customer-caller'])assert.equal((await call(fixture({uid}),body)).statusCode,403);for(const mutate of [
  f=>f.state.set('tenants/tenant-a/employees/employee-a',{authUid:'different',email:'avery@example.test',status:'active'}),
  f=>f.state.set('users/employee-a',{role:'employee',status:'active',tenantId:'tenant-b',email:'avery@example.test'}),
  f=>f.state.set('users/employee-a',{role:'employee',status:'inactive',tenantId:'tenant-a',email:'avery@example.test'}),
  f=>f.state.set('tenants/tenant-a/employees/employee-a',{authUid:'employee-a',email:'other@example.test',status:'active'}),
]){const f=fixture();f.state.set('users/employee-a',{role:'employee',status:'active',tenantId:'tenant-a',email:'avery@example.test'});f.state.set('tenants/tenant-a/employees/employee-a',{authUid:'employee-a',email:'avery@example.test',status:'active'});f.state.set('tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','employee-a']});mutate(f);assert.equal((await call(f,body)).statusCode,404);assert.notEqual(f.state.get('tenants/tenant-a/employees/employee-a')?.canCollectPayments,true);}const legacy=fixture();legacy.state.set('tenants/tenant-a/employees/legacy-random',{email:'legacy@example.test',status:'active'});assert.equal((await call(legacy,{...body,employeeUid:'legacy-random'})).statusCode,404);});
test('resend uses existing identity and never creates another Auth user',async()=>{const f=fixture();await call(f);const employee=[...f.users.values()][0];const record=f.state.get(`tenants/tenant-a/employees/${employee.uid}`);record.activationEmailLastAttemptAt='2000-01-01T00:00:00.000Z';f.sent.length=0;const res=await call(f,{action:'owner_resend_activation',email:'avery@example.test'});assert.equal(res.statusCode,200);assert.equal(f.users.size,1);assert.equal(f.sent.length,1);});
test('immediate activation resend is rate limited',async()=>{const f=fixture();await call(f);assert.equal((await call(f,{action:'owner_resend_activation',email:'avery@example.test'})).statusCode,429);assert.equal(f.users.size,1);});
test('conflicting employee profile email under another UID is denied',async()=>{const f=fixture();f.state.set('tenants/tenant-a/employees/conflict',{email:'avery@example.test',status:'active'});assert.equal((await call(f)).statusCode,409);assert.equal(f.users.size,0);});
test('pre-existing canonical Auth user is never deleted when activation delivery fails',async()=>{const f=fixture({authUsers:{existing:{uid:'existing',email:'avery@example.test'}}});f.state.set('users/existing',{role:'employee',status:'active',tenantId:'tenant-a',email:'avery@example.test'});f.state.set('tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','existing']});f.state.set('tenants/tenant-a/employees/existing',{authUid:'existing',name:'Avery',email:'avery@example.test',phone:'',status:'active',activationStatus:'delivery_failed'});f.sendActivationEmail=async()=>{throw new Error('down');};const record=f.state.get('tenants/tenant-a/employees/existing');record.activationEmailLastAttemptAt='2000-01-01T00:00:00.000Z';assert.equal((await call(f,{action:'owner_resend_activation',email:'avery@example.test'})).statusCode,503);assert.deepEqual(f.deleted,[]);assert.equal(f.users.has('existing'),true);});
test('activation sender fails closed when provider is disabled and never calls provider',async()=>{const fetchImpl=async()=>{throw new Error('must not call');};const sender=createResendActivationSender({apiKey:'key',fetchImpl,providerEnabled:false});await assert.rejects(()=>sender({email:'a@example.test',name:'A',actionLink:'https://example.test/reset',operationId:'attempt'}),/disabled/);});
