const assert=require('node:assert/strict');
const {test}=require('node:test');
const fs=require('node:fs');
const path=require('node:path');
const {MAX_ITEMS,createServiceCatalogGatewayHandler,parseRequest}=require('../serviceCatalogGateway');

function fixture({uid='owner-a',profile={},tenant={},services={}}={}){
  const data=new Map([['users/owner-a',{role:'admin',status:'active',tenantId:'tenant-a'}],['users/employee-a',{role:'employee',status:'active',tenantId:'tenant-a'}],['users/customer-a',{role:'customer',status:'active',tenantId:'tenant-a'}],['tenants/tenant-a',{adminUsers:['owner-a'],users:['owner-a','employee-a']}]]);
  data.set(`users/${uid}`,{...(data.get(`users/${uid}`)||{}),...profile});data.set('tenants/tenant-a',{...data.get('tenants/tenant-a'),...tenant});Object.entries(services).forEach(([id,value])=>data.set(`tenants/tenant-a/serviceCatalog/${id}`,value));let sequence=0;
  class Ref{constructor(path){this.path=path;this.id=path.split('/').at(-1);}doc(id){return new Ref(`${this.path}/${id||`generated-${++sequence}`}`);}collection(name){return new Query(`${this.path}/${name}`);}async get(){return{exists:data.has(this.path),data:()=>data.get(this.path)};}async create(value){data.set(this.path,structuredClone(value));}async update(value){data.set(this.path,{...data.get(this.path),...structuredClone(value)});}}
  class Query{constructor(path){this.path=path;}doc(id){return new Ref(`${this.path}/${id||`generated-${++sequence}`}`);}limit(value){assert.equal(value,MAX_ITEMS);return this;}async get(){const prefix=`${this.path}/`;return{docs:[...data].filter(([path])=>path.startsWith(prefix)&&!path.slice(prefix.length).includes('/')).map(([path,value])=>({id:path.slice(prefix.length),data:()=>value}))};}}
  return{data,admin:{auth:()=>({verifyIdToken:async()=>({uid})}),firestore:()=>({collection:name=>new Query(name)})}};
}
function response(){return{statusCode:0,body:null,set(){return this;},status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;},send(body){this.body=body;return this;}};}
async function call(source,body,headers={authorization:'Bearer fake'}){const res=response();await createServiceCatalogGatewayHandler({admin:source.admin})({method:'POST',headers,body},res);return res;}
const valid={action:'owner_create',name:'Standard clean',serviceType:'standard',active:true,priceCents:15000,durationMinutes:120};

test('owner creates, updates, and deactivates a stable service',async()=>{const source=fixture();const created=await call(source,valid);assert.equal(created.statusCode,200);const id=created.body.service.id;const updated=await call(source,{...valid,action:'owner_update',serviceId:id,active:false,priceCents:17500});assert.deepEqual(updated.body.service,{id,name:'Standard clean',serviceType:'standard',active:false,priceCents:17500,durationMinutes:120});assert.equal(source.data.get(`tenants/tenant-a/serviceCatalog/${id}`).createdByUid,'owner-a');});
test('strict contract rejects forged authority, actors, timestamps, and invalid values',()=>{for(const field of ['tenantId','uid','role','createdAt','updatedByUid'])assert.throws(()=>parseRequest({...valid,[field]:'forged'}));for(const patch of [{priceCents:0},{priceCents:1.5},{durationMinutes:0},{durationMinutes:1.5},{serviceType:'carpet'}])assert.throws(()=>parseRequest({...valid,...patch}),error=>error.code==='validation_failed');});
test('employee, customer, wrong tenant membership, and unauthenticated caller are denied',async()=>{assert.equal((await call(fixture({uid:'employee-a'}),valid)).statusCode,403);assert.equal((await call(fixture({uid:'customer-a'}),valid)).statusCode,403);assert.equal((await call(fixture({tenant:{adminUsers:['other']}}),valid)).statusCode,403);assert.equal((await call(fixture(),valid,{})).statusCode,401);});
test('owner list returns only the canonical tenant collection',async()=>{const source=fixture({services:{one:{name:'Deep clean',serviceType:'deep',active:true,priceCents:20000,durationMinutes:180,createdByUid:'hidden'}}});const result=await call(source,{action:'owner_list'});assert.deepEqual(result.body,{success:true,services:[{id:'one',name:'Deep clean',serviceType:'deep',active:true,priceCents:20000,durationMinutes:180}]});});
test('bounded catalog rejects service 51',async()=>{const services=Object.fromEntries(Array.from({length:MAX_ITEMS},(_,i)=>[`s${i}`,{name:`Service ${i}`,serviceType:'standard',active:true,priceCents:10000,durationMinutes:60}]));const result=await call(fixture({services}),valid);assert.equal(result.statusCode,409);assert.equal(result.body.code,'catalog_limit');});
test('deployed service catalog gateway is bounded and secret-free',()=>{const source=fs.readFileSync(path.join(__dirname,'..','index.js'),'utf8');assert.match(source,/exports\.serviceCatalogGateway = functions\.runWith\(\{ minInstances: 0, maxInstances: 3 \}\)/);assert.doesNotMatch(source,/exports\.serviceCatalogGateway[\s\S]{0,100}secrets:/);});
