const { buildEmployeeFunctionUrl } = require('./employeeSessionClient');
class ExtraWorkClientError extends Error{constructor(message,code='extra_work_unavailable'){super(message);this.code=code;}}
function createExtraWorkClient({auth,runtimeConfig,fetchImpl}){async function call(functionName,body){const user=auth.currentUser;if(!user?.getIdToken)throw new ExtraWorkClientError('Sign in to submit an extra-work request.','unauthenticated');const response=await fetchImpl(buildEmployeeFunctionUrl(runtimeConfig,functionName),{method:'POST',headers:{Authorization:`Bearer ${await user.getIdToken()}`,'Content-Type':'application/json'},body:JSON.stringify(body)});let payload;try{payload=await response.json();}catch{throw new ExtraWorkClientError('Extra-work requests are temporarily unavailable.');}if(!response.ok)throw new ExtraWorkClientError('Extra-work request could not be processed.',payload?.code);return payload;}
  return{
    async listCatalog(){const payload=await call('addOnCatalogGateway',{action:'employee_list_active'});return Array.isArray(payload.addOns)?payload.addOns.map(item=>({id:String(item.id||''),label:String(item.label||''),priceCents:Number(item.priceCents)||0,durationMinutes:Number(item.durationMinutes)||0})):[];},
    async listRequests(bookingId){const payload=await call('extraWorkGateway',{action:'employee_list',bookingId});return Array.isArray(payload.requests)?payload.requests.map(item=>({id:String(item.id||''),status:String(item.status||''),requestedAt:String(item.requestedAt||''),items:Array.isArray(item.items)?item.items.map(value=>({id:String(value.id||''),label:String(value.label||''),quantity:Number(value.quantity)||0,lineTotalCents:Number(value.lineTotalCents)||0,durationMinutes:Number(value.durationMinutes)||0})):[],customRequest:item.customRequest?{description:String(item.customRequest.description||'')}:null,disposition:item.disposition?String(item.disposition):null})):[];},
    async submitRequest(bookingId,{items,customRequest,employeeNote}){const payload=await call('extraWorkGateway',{action:'employee_submit',bookingId,items:items.map(item=>({addOnId:item.addOnId,quantity:item.quantity})),customRequest:customRequest?{description:customRequest.description,context:customRequest.context}:null,employeeNote});return payload.request;},
  };
}
module.exports={ExtraWorkClientError,createExtraWorkClient};
