import { auth } from '../firebase';
import { resolveOwnerOnboardingGatewayUrl } from './ownerOnboardingService';

export class EmployeeTeamServiceError extends Error { constructor(message,code='team_unavailable'){super(message);this.name='EmployeeTeamServiceError';this.code=code;} }
function employee(value){if(!value||typeof value!=='object'||typeof value.uid!=='string'||!value.uid.trim()||typeof value.name!=='string'||typeof value.email!=='string'||!['active','inactive'].includes(value.status)||typeof value.activationStatus!=='string')throw new EmployeeTeamServiceError('Employee team service returned invalid data.','invalid_response');return{uid:value.uid.trim(),name:value.name.trim(),email:value.email.trim().toLowerCase(),phone:typeof value.phone==='string'?value.phone.trim():'',status:value.status,activationStatus:value.activationStatus.trim()};}
async function call(body,{user=auth.currentUser,fetchImpl=fetch}={}){if(!user?.getIdToken)throw new EmployeeTeamServiceError('Sign in to manage employees.','unauthenticated');const response=await fetchImpl(resolveOwnerOnboardingGatewayUrl(import.meta.env,'employeeTeamGateway'),{method:'POST',headers:{Authorization:`Bearer ${await user.getIdToken()}`,'Content-Type':'application/json'},body:JSON.stringify(body)});let payload;try{payload=await response.json();}catch{throw new EmployeeTeamServiceError('Employee team service is unavailable.');}if(!response.ok)throw new EmployeeTeamServiceError('Employee team update could not be completed.',payload?.code);return payload;}
export async function listCanonicalEmployees(options){const payload=await call({action:'owner_list'},options);if(!Array.isArray(payload.employees)||![null,'owner_only','employees'].includes(payload.workforceMode))throw new EmployeeTeamServiceError('Employee team service returned invalid data.','invalid_response');return{employees:payload.employees.map(employee),workforceMode:payload.workforceMode};}
export async function provisionEmployee(values,options){const payload=await call({action:'owner_provision',name:values.name,email:values.email,phone:values.phone||''},options);return{success:payload.success===true,reused:payload.reused===true,employee:employee(payload.employee)};}
export async function resendEmployeeActivation(email,options){const payload=await call({action:'owner_resend_activation',email},options);return{success:payload.success===true,reused:payload.reused===true,employee:employee(payload.employee)};}
export const setWorkforceMode=(workforceMode,options)=>call({action:'owner_set_workforce_mode',workforceMode},options);
